#!/usr/bin/env python3
"""このリポジトリのスキルを、指定したエージェントから呼べるように登録する。

    python3 install.py <provider> [skill ...] [--dest DIR] [--dry-run]

実体は各スキルのディレクトリに置いたまま、プロバイダごとの規約に合わせた薄い
「アダプタ」ファイルだけを生成する。アダプタは instructions.md への絶対パスを
持つポインタなので、中身の更新は git pull だけで反映される。

標準ライブラリのみ。macOS / Linux / Windows で同じように動く。
"""

import argparse
import sys
from pathlib import Path

if sys.version_info < (3, 8):
    sys.exit("Python 3.8 以降が必要です（現在: %s）" % sys.version.split()[0])

REPO_ROOT = Path(__file__).resolve().parent
MARKER = "<!-- generated by inouelab-skills install.py -- do not edit -->"


# --- スキルの読み出し ---------------------------------------------------


class Skill:
    def __init__(self, directory: Path):
        self.dir = directory
        self.name, self.description = _read_meta(directory / "skill.yaml")

    @property
    def posix_dir(self) -> str:
        """埋め込み用のパス。

        Windows でも区切りは `/` に統一する。バックスラッシュは Markdown でも
        YAML でも TOML でもエスケープ文字になるうえ、各エージェントは `/` を
        問題なく解決するため。
        """
        return self.dir.as_posix()


def _read_meta(path: Path):
    """skill.yaml から name と description だけを取り出す。

    PyYAML に依存しないための最小パーサ。`description: >-` による複数行の
    折りたたみに対応する。それ以外の YAML 機能は使わないこと。
    """
    name = ""
    desc_parts = []
    in_desc = False

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        if not line:
            continue

        if line.startswith("name:"):
            in_desc = False
            name = line[len("name:"):].strip()
        elif line.startswith("description:"):
            in_desc = True
            first = line[len("description:"):].strip()
            # >- / > / | / |- は「次行から本文」を示す記号なので本文ではない
            if first not in (">", ">-", "|", "|-"):
                desc_parts.append(first)
        elif line[0].isspace():
            if in_desc:
                desc_parts.append(line.strip())
        else:
            in_desc = False

    description = " ".join(p for p in desc_parts if p)
    if not name:
        raise ValueError(f"skill.yaml に name がありません: {path}")
    if not description:
        raise ValueError(f"skill.yaml に description がありません: {path}")
    return name, description


def discover(names=None):
    if names:
        dirs = [REPO_ROOT / n for n in names]
    else:
        dirs = sorted(d for d in REPO_ROOT.iterdir() if d.is_dir())

    skills = []
    for d in dirs:
        if (d / "instructions.md").is_file() and (d / "skill.yaml").is_file():
            skills.append(Skill(d))
        elif names:
            print(f"skip  {d.name}  (instructions.md か skill.yaml がない)", file=sys.stderr)
    return skills


# --- 埋め込み用エスケープ -----------------------------------------------


def yaml_squote(s: str) -> str:
    """YAML 単一引用符スカラー。内部の ' を '' にする。"""
    return "'" + s.replace("'", "''") + "'"


def toml_basic(s: str) -> str:
    """TOML 基本文字列。\\ と " を退避する。"""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


# --- アダプタ本文 -------------------------------------------------------


def body(skill: Skill) -> str:
    """どのプロバイダでも共通。instructions.md を読ませ、参照の基準を教える。"""
    d = skill.posix_dir
    return f"""{MARKER}

# {skill.name}

{skill.description}

このスキルの手順は次のファイルにある。**最初にこれを読み、書かれているとおりに進めること。**

    {d}/instructions.md

参照ドキュメントは `{d}/references/` にある。instructions.md 内の相対パスは
`{d}/` を基準に解決する。手順が「読め」と指示したタイミングで実際にファイルを
開くこと。内容を推測で埋めない。
"""


# --- プロバイダ ---------------------------------------------------------
# 生成先を返す関数と、本文の包み方。ここだけがプロバイダ依存。

HOME = Path.home()


def _claude(s, dest):
    return HOME / ".claude" / "skills" / s.name / "SKILL.md", (
        f"---\nname: {s.name}\ndescription: {yaml_squote(s.description)}\n---\n\n{body(s)}"
    )


def _codex(s, dest):
    return HOME / ".agents" / "skills" / s.name / "SKILL.md", (
        f"---\nname: {s.name}\ndescription: {yaml_squote(s.description)}\n---\n\n{body(s)}"
    )


def _copilot(s, dest):
    return dest / ".github" / "prompts" / f"{s.name}.prompt.md", (
        f"---\ndescription: {yaml_squote(s.description)}\n---\n\n{body(s)}"
    )


def _cursor(s, dest):
    return dest / ".cursor" / "rules" / f"{s.name}.mdc", (
        f"---\ndescription: {yaml_squote(s.description)}\nalwaysApply: false\n---\n\n{body(s)}"
    )


def _gemini(s, dest):
    return HOME / ".gemini" / "commands" / f"{s.name}.toml", (
        f"description = {toml_basic(s.description)}\n"
        f"prompt = '''\n{body(s)}\n{{{{args}}}}\n'''\n"
    )


PROVIDERS = {
    "claude":  ("Claude Code",      "~/.claude/skills/<name>/SKILL.md",           _claude),
    "codex":   ("OpenAI Codex",     "~/.agents/skills/<name>/SKILL.md",          _codex),
    "copilot": ("GitHub Copilot",   "<dest>/.github/prompts/<name>.prompt.md",    _copilot),
    "cursor":  ("Cursor",           "<dest>/.cursor/rules/<name>.mdc",            _cursor),
    "gemini":  ("Gemini CLI",       "~/.gemini/commands/<name>.toml",             _gemini),
    "manual":  ("それ以外",          "標準出力",                                    None),
}

REPO_SCOPED = {"copilot", "cursor"}


# --- 書き込み -----------------------------------------------------------


def write_adapter(path: Path, content: str, dry_run: bool) -> None:
    if dry_run:
        print(f"--- {path}")
        print(content)
        return

    if path.exists():
        try:
            existing = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            existing = ""
        if MARKER not in existing:
            print(
                f"skip  {path}  (このスクリプトが生成したものではないため上書きしません)",
                file=sys.stderr,
            )
            return

    path.parent.mkdir(parents=True, exist_ok=True)
    # 改行は LF に固定する。Windows で CRLF になると差分が読みにくくなるため。
    # Path.write_text の newline 引数は 3.10 以降なので open() を使う。
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print(f"write {path}")


# --- エントリポイント ---------------------------------------------------


def build_parser():
    providers = "\n".join(
        f"  {k:<9} {label:<18} {where}" for k, (label, where, _) in PROVIDERS.items()
    )
    p = argparse.ArgumentParser(
        prog="install.py",
        description="スキルを各エージェントに登録する",
        epilog=f"providers:\n{providers}\n\n"
               "skill を省略するとリポジトリ内の全スキルを対象にする。\n\n"
               "例:\n"
               "  python3 install.py claude\n"
               "  python3 install.py copilot slide-review --dest ~/work/my-project\n"
               "  python3 install.py manual slide-review\n",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("provider", choices=list(PROVIDERS))
    p.add_argument("skills", nargs="*", help="対象スキル名（省略時は全部）")
    p.add_argument("--dest", default=None,
                   help="copilot / cursor の設置先リポジトリ（既定: カレントディレクトリ）")
    p.add_argument("--dry-run", action="store_true",
                   help="生成せず、書き込み先と内容を表示する")
    return p


def main(argv=None):
    args = build_parser().parse_args(argv)

    dest = Path(args.dest).expanduser().resolve() if args.dest else Path.cwd()
    if args.provider in REPO_SCOPED and args.dest is None:
        print(f"note  {args.provider} はリポジトリ単位です。設置先: {dest}")
        print("      別のリポジトリに入れる場合は --dest を指定してください。\n")

    try:
        skills = discover(args.skills or None)
    except ValueError as e:
        print(e, file=sys.stderr)
        return 1

    if not skills:
        print("スキルが見つかりません（instructions.md と skill.yaml を持つ"
              "ディレクトリがリポジトリ直下にない）", file=sys.stderr)
        return 1

    if args.provider == "manual":
        for s in skills:
            print(f"=== {s.name} ===")
            print("以下を、使っているエージェントのカスタム指示 / プロンプトとして登録してください。\n")
            print(body(s))
        return 0

    _, _, adapter = PROVIDERS[args.provider]
    for s in skills:
        path, content = adapter(s, dest)
        write_adapter(path, content, args.dry_run)

    if not args.dry_run:
        print("\n完了。新しいセッションから使えます。")
        print(f"スキルの中身は {REPO_ROOT} 以下にあります。更新は git pull だけで反映されます")
        print("（name / description を変えたときだけ、このスクリプトを再実行してください）。")
    return 0


if __name__ == "__main__":
    sys.exit(main())
